version: '3.7'
services:
#  nginx:
#    image: nginx:1.17
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 8000:80
#    depends_on:
#      - backend
#      - frontend

#  redis:
#    image: redis
#    ports:
#      - 6379:6379

#  mailhog:
#    image: mailhog/mailhog
#    logging:
#      driver: 'none'  # disable saving logs
#    ports:
#      - 1025:1025 # smtp server
#      - 8025:8025 # web ui

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pudop
      POSTGRES_DB: uptime
    ports:
      - '5632:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  #  worker:
  #    build:
  #      context: backend
  #      dockerfile: Dockerfile
  #    command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1

  #  flower:
  #    image: mher/flower
  #    command: celery flower --broker=redis://redis:6379/0 --port=5555
  #    ports:
  #        - 5555:5555
  #    depends_on:
  #      - "redis"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/:cached
    environment:
#      DATABASE_URL: 'postgresql://postgres:pudop@db:5432/uptime'
      DATABASE_HOST: 'db'
    depends_on:
      - "db"

#  frontend:
#    build:
#      context: frontend
#      dockerfile: Dockerfile
#    stdin_open: true
#    volumes:
#      - './frontend:/app:cached'
#      - './frontend/node_modules:/app/node_modules:cached'
#    environment:
#      - NODE_ENV=development


volumes:
  db-data:
