# Generated by Django 4.1.2 on 2022-11-05 20:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Friendly name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("up", "UP"),
                            ("down", "DOWN"),
                            ("down", "FAIL"),
                            ("paused", "PAUSED"),
                        ],
                        default="checking",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is active"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("ws", "WebSocket"),
                            ("icmp-ping", "ICMP-PING"),
                            ("incoming", "Incoming request"),
                        ],
                        max_length=10,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Endpoint"
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Port"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                (
                    "check_interval",
                    models.DurationField(default="PT1M", verbose_name="Check interval"),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last checked"
                    ),
                ),
                (
                    "availability",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Percentage availability"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="ServiceNotify",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delay",
                    models.PositiveIntegerField(default=0, verbose_name="Notify delay"),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Additional message",
                    ),
                ),
                ("channel", models.CharField(max_length=100, verbose_name="Channel")),
                ("configuration", models.JSONField(verbose_name="Configuration")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("id",),
            },
        ),
    ]
