# Generated by Django 4.1.2 on 2022-11-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_organizationuser_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
    ]
